import type { DirectorPlan } from '../store/types';

const MOCK_PLANS: DirectorPlan[] = [
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '傘',
        voxels: [
            { pos: [2, 0, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 1, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 2, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [0, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [1, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [3, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [4, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [1, 4, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 4, 2], color: '#FF3B30', type: 'standard' },
            { pos: [3, 4, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 1], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 3], color: '#FF3B30', type: 'standard' },
        ],
        vibe_vector: { warmth: 2, density: 2, focus: 4, randomness: 0, saturation: 3, verticality: 3 },
        hint_foundation: [
            { pos: [2, 0, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 2, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 4, 2], color: '#FF3B30', type: 'standard' },
            { pos: [0, 3, 2], color: '#FF3B30', type: 'standard' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: 'きのこ',
        voxels: [
            { pos: [2, 0, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [1, 2, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 2, 2], color: '#FF3B30', type: 'standard' },
            { pos: [3, 2, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 2, 1], color: '#FF3B30', type: 'standard' },
            { pos: [2, 2, 3], color: '#FF3B30', type: 'standard' },
            { pos: [1, 3, 1], color: '#FF3B30', type: 'standard' },
            { pos: [1, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [1, 3, 3], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 1], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 3], color: '#FF3B30', type: 'standard' },
            { pos: [3, 3, 1], color: '#FF3B30', type: 'standard' },
            { pos: [3, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [3, 3, 3], color: '#FF3B30', type: 'standard' },
            { pos: [2, 4, 2], color: '#FF3B30', type: 'standard' },
        ],
        vibe_vector: { warmth: 2, density: 3, focus: 4, randomness: 0, saturation: 3, verticality: 3 },
        hint_foundation: [
            { pos: [2, 0, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 3, 2], color: '#FF3B30', type: 'standard' },
            { pos: [1, 3, 1], color: '#FF3B30', type: 'standard' },
            { pos: [3, 3, 3], color: '#FF3B30', type: 'standard' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '小さな家',
        voxels: [
            { pos: [1, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 0, 2], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 2], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 1, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 1, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 1, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 1, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 1, 1], color: '#0A84FF', type: 'transparent' },
            { pos: [1, 2, 1], color: '#FF3B30', type: 'standard' },
            { pos: [2, 2, 1], color: '#FF3B30', type: 'standard' },
            { pos: [3, 2, 1], color: '#FF3B30', type: 'standard' },
            { pos: [1, 2, 3], color: '#FF3B30', type: 'standard' },
            { pos: [2, 2, 3], color: '#FF3B30', type: 'standard' },
            { pos: [3, 2, 3], color: '#FF3B30', type: 'standard' },
            { pos: [2, 3, 2], color: '#FF3B30', type: 'standard' },
        ],
        vibe_vector: { warmth: 3, density: 3, focus: 4, randomness: 0, saturation: 3, verticality: 2 },
        hint_foundation: [
            { pos: [1, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 3, 2], color: '#FF3B30', type: 'standard' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '一本の木',
        voxels: [
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 1, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 2, 2], color: '#8B4513', type: 'standard' },
            { pos: [1, 3, 2], color: '#30D158', type: 'standard' },
            { pos: [2, 3, 2], color: '#30D158', type: 'standard' },
            { pos: [3, 3, 2], color: '#30D158', type: 'standard' },
            { pos: [2, 3, 1], color: '#30D158', type: 'standard' },
            { pos: [2, 3, 3], color: '#30D158', type: 'standard' },
            { pos: [1, 4, 2], color: '#30D158', type: 'standard' },
            { pos: [3, 4, 2], color: '#30D158', type: 'standard' },
            { pos: [2, 4, 1], color: '#30D158', type: 'standard' },
            { pos: [2, 4, 3], color: '#30D158', type: 'standard' },
            { pos: [2, 4, 2], color: '#30D158', type: 'standard' },
        ],
        vibe_vector: { warmth: 2, density: 2, focus: 4, randomness: 1, saturation: 3, verticality: 4 },
        hint_foundation: [
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 1, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 2, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 4, 2], color: '#30D158', type: 'standard' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '塔',
        voxels: [
            { pos: [2, 0, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 2, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 3, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 4, 2], color: '#FFD60A', type: 'emissive' },
            { pos: [1, 0, 1], color: '#1E2D3D', type: 'standard' },
            { pos: [3, 0, 1], color: '#1E2D3D', type: 'standard' },
            { pos: [1, 0, 3], color: '#1E2D3D', type: 'standard' },
            { pos: [3, 0, 3], color: '#1E2D3D', type: 'standard' },
            { pos: [1, 0, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [3, 0, 2], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 0, 1], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 0, 3], color: '#1E2D3D', type: 'standard' },
        ],
        vibe_vector: { warmth: 1, density: 2, focus: 4, randomness: 0, saturation: 1, verticality: 4 },
        hint_foundation: [
            { pos: [1, 0, 1], color: '#1E2D3D', type: 'standard' },
            { pos: [3, 0, 3], color: '#1E2D3D', type: 'standard' },
            { pos: [2, 0, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 4, 2], color: '#FFD60A', type: 'emissive' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '剣',
        voxels: [
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [1, 1, 2], color: '#FFD60A', type: 'standard' },
            { pos: [3, 1, 2], color: '#FFD60A', type: 'standard' },
            { pos: [2, 2, 2], color: '#E0F0FF', type: 'emissive' },
            { pos: [2, 3, 2], color: '#E0F0FF', type: 'emissive' },
            { pos: [2, 4, 2], color: '#E0F0FF', type: 'emissive' },
        ],
        vibe_vector: { warmth: 1, density: 1, focus: 4, randomness: 0, saturation: 1, verticality: 4 },
        hint_foundation: [
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [1, 1, 2], color: '#FFD60A', type: 'standard' },
            { pos: [3, 1, 2], color: '#FFD60A', type: 'standard' },
            { pos: [2, 4, 2], color: '#E0F0FF', type: 'emissive' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: 'ケーキ',
        voxels: [
            { pos: [1, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 0, 2], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 0, 2], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 2], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [1, 1, 1], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 1], color: '#E0F0FF', type: 'standard' },
            { pos: [3, 1, 1], color: '#E0F0FF', type: 'standard' },
            { pos: [1, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [3, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [1, 1, 3], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 1, 3], color: '#E0F0FF', type: 'standard' },
            { pos: [3, 1, 3], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 2, 2], color: '#FF3B30', type: 'emissive' },
        ],
        vibe_vector: { warmth: 4, density: 4, focus: 3, randomness: 0, saturation: 3, verticality: 1 },
        hint_foundation: [
            { pos: [1, 0, 1], color: '#FF9F0A', type: 'standard' },
            { pos: [3, 0, 3], color: '#FF9F0A', type: 'standard' },
            { pos: [2, 1, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 2, 2], color: '#FF3B30', type: 'emissive' },
        ],
    },
    {
        grid_size: [5, 5, 5],
        vibe_prompt: '船',
        voxels: [
            { pos: [0, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [1, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [3, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [4, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [1, 0, 1], color: '#8B4513', type: 'standard' },
            { pos: [2, 0, 1], color: '#8B4513', type: 'standard' },
            { pos: [3, 0, 1], color: '#8B4513', type: 'standard' },
            { pos: [1, 0, 3], color: '#8B4513', type: 'standard' },
            { pos: [2, 0, 3], color: '#8B4513', type: 'standard' },
            { pos: [3, 0, 3], color: '#8B4513', type: 'standard' },
            { pos: [2, 1, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 2, 2], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 2, 1], color: '#E0F0FF', type: 'standard' },
            { pos: [2, 2, 3], color: '#E0F0FF', type: 'standard' },
        ],
        vibe_vector: { warmth: 2, density: 3, focus: 3, randomness: 0, saturation: 2, verticality: 1 },
        hint_foundation: [
            { pos: [0, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [4, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 0, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 1, 2], color: '#8B4513', type: 'standard' },
            { pos: [2, 2, 2], color: '#E0F0FF', type: 'standard' },
        ],
    },
];

export function generateMockDirectorPlan(): DirectorPlan {
    return MOCK_PLANS[Math.floor(Math.random() * MOCK_PLANS.length)];
}
